# Generated by Django 2.1.2 on 2018-12-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20181129_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='uid',
            field=models.CharField(default='0', max_length=18),
        ),
    ]
