# Generated by Django 2.1.2 on 2018-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='express_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=18)),
                ('order_ID', models.CharField(max_length=32, null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('security_check_time', models.DateTimeField(null=True)),
                ('save_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
